import { Injectable } from '@angular/core';
import { REGISTRY_FOR_JS, FUNCTION_REGISTRY } from './function-registry';

export type JsFunction = (x: number) => number;

/**
 * Translates a Maxima expression string into an evaluable JS function.
 *
 * Supported functions are derived from FUNCTION_REGISTRY in function-registry.ts.
 * Adding a new function to the registry automatically extends support here
 * without any changes to this file (unless a new _helper implementation is needed).
 *
 * SSR-safe: no DOM dependencies.
 */
@Injectable({ providedIn: 'root' })
export class MathUtilsService {

  // ── Compile cache ──────────────────────────────────────────────────────────
  //
  // `compile()` is called on every RAF frame for every visible curve — once per
  // slider tick when parameters change. Without a cache, `new Function` is
  // invoked repeatedly for the same expression string, wasting CPU.
  //
  // Key format: `variable::maximaSource::paramJSON` so that the same expression
  // with different parameter values maps to distinct entries.
  //
  // Size is bounded by LRU eviction: when the Map exceeds COMPILE_CACHE_MAX
  // entries, the oldest entry (first inserted) is removed. Map iteration order
  // is insertion order, so `map.keys().next()` is always the oldest key.
  private readonly _compileCache = new Map<string, JsFunction | null>();
  private static readonly COMPILE_CACHE_MAX = 256;

  /**
   * Compiles a Maxima expression string to a JS function of `variable` (default `'x'`).
   * If `params` is provided, those symbol→value substitutions are applied to the
   * Maxima string BEFORE the conversion pipeline, allowing parametric expressions
   * (e.g. `exp(-a*t)` with `{a: 2}`) to be evaluated numerically.
   *
   * Results are memoised: identical (maxima, variable, params) tuples return the
   * same function object from cache on subsequent calls — no `new Function` overhead.
   *
   * Returns null only if the JS generated by the Maxima→JS pipeline cannot be
   * parsed by the JS engine (syntax error). Functions that return NaN for all
   * inputs are returned as-is; the sampler filters those values naturally.
   * This means `sqrt(-x)` is now a valid compilation result (previously rejected
   * because all smoke-test points were NaN).
   */
  compile(maxima: string, variable = 'x', params?: Record<string, number>): JsFunction | null {
    if (!maxima.trim()) return null;

    const cacheKey = `${variable}::${maxima}::${params ? JSON.stringify(params) : ''}`;
    if (this._compileCache.has(cacheKey)) return this._compileCache.get(cacheKey)!;

    const fn = this._compileUncached(maxima, variable, params);

    // LRU eviction: drop oldest entry when cache is full
    if (this._compileCache.size >= MathUtilsService.COMPILE_CACHE_MAX) {
      const oldest = this._compileCache.keys().next().value;
      if (oldest !== undefined) this._compileCache.delete(oldest);
    }
    this._compileCache.set(cacheKey, fn);
    return fn;
  }

  /**
   * Compiles without touching the cache. Called only by `compile()`.
   *
   * Smoke-test removed: if `new Function` succeeds, the function is returned
   * even if it returns NaN for all test points. The maths sampler already skips
   * non-finite values via `isFinite(y)`, so rejecting here only caused false
   * negatives (e.g. `sqrt(-x)` for x > 0, or any function undefined at 0).
   */
  private _compileUncached(
    maxima: string,
    variable: string,
    params?: Record<string, number>,
  ): JsFunction | null {
    try {
      let expr = maxima;
      if (params) {
        for (const [name, value] of Object.entries(params)) {
          // Word-boundary replacement: won't touch 'a' inside 'abs', 'atan', etc.
          // Always wrap in parens so negative values don't create `--` decrement ops.
          expr = expr.replace(new RegExp(`\\b${name}\\b`, 'g'), `(${String(value)})`);
        }
      }
      const js = this.maximaToJs(expr);
      // eslint-disable-next-line no-new-func
      return new Function(variable, `"use strict"; ${this._helpers} return (${js});`) as JsFunction;
    } catch {
      return null;
    }
  }

  /**
   * Evaluates a Maxima expression at a given value.
   * Returns NaN if compilation fails or the result is non-finite.
   */
  evaluate(maxima: string, x: number, variable = 'x'): number {
    const fn = this.compile(maxima, variable);
    if (!fn) return NaN;
    try {
      const result = fn(x);
      return isFinite(result) ? result : NaN;
    } catch {
      return NaN;
    }
  }

  /**
   * Samples a Maxima expression over [from, to] with `n` points.
   * Returns an array of { x, y } pairs, skipping NaN results.
   */
  sample(
    maxima: string,
    from: number,
    to: number,
    n = 500,
    variable = 'x',
  ): { x: number; y: number }[] {
    const fn = this.compile(maxima, variable);
    if (!fn) return [];

    const points: { x: number; y: number }[] = [];
    const step = (to - from) / (n - 1);

    for (let i = 0; i < n; i++) {
      const x = from + i * step;
      try {
        const y = fn(x);
        if (isFinite(y)) points.push({ x, y });
      } catch {
        // skip discontinuities
      }
    }
    return points;
  }

  // ── Translation ────────────────────────────────────────────────────────────

  private maximaToJs(expr: string): string {
    let s = expr
      // Constants — order matters: %pi before %i so %pi isn't consumed by %i
      .replace(/%pi\b/g, 'Math.PI')
      .replace(/%e\b/g, 'Math.E')
      // Imaginary unit: treat as 0 for real-valued plotting (Re/Im already separated by backend)
      .replace(/%i\b/g, '0')
      .replace(/\binf\b/g, 'Infinity')
      // Power operator: ^ → **
      .replace(/\^/g, '**');

    // Convert Math.E**BARE (non-parenthesised negative exponents like -t**2) to
    // Math.exp(BARE) before _fixUnaryMinusPow, which cannot handle exponents that
    // start with '-'. Must run before the registry loop would re-process 'exp';
    // the registry regex now has (?<!\.) to skip already-prefixed Math.exp calls.
    s = this._convertMathEPowBare(s);

    // JS forbids a unary '-' as the direct left operand of '**' (SyntaxError).
    // Fix both -IDENTIFIER** and -(expr)** before any further substitutions touch them.
    s = this._fixUnaryMinusPow(s);

    // sgn is a Maxima alias for sign — normalize before the registry loop runs.
    s = s.replace(/\bsgn\b\s*\(/g, 'sign(');

    // Apply all function translations from REGISTRY_FOR_JS (sorted longest-first
    // so 'asinh' matches before 'sinh', 'atanh' before 'tanh', etc.)
    for (const fn of REGISTRY_FOR_JS) {
      // Negative lookbehind (?<!\.) prevents matching method names already prefixed
      // with 'Math.' (e.g. the 'exp' in 'Math.exp' produced by _convertMathEPowBare).
      const re = new RegExp(`(?<!\\.)\\b${fn.maxima}\\b`, 'g');
      const { js } = fn;
      if (js.kind === 'Math') {
        s = s.replace(re, `Math.${js.method}`);
      } else if (js.kind === 'helper') {
        s = s.replace(re, js.name);
      } else if (js.kind === 'inline') {
        // Inline replacements need paren-aware matching; handled after the loop.
        // Skip here — _applyInlineReplacements() handles them.
      }
      // kind === 'stub': signal functions handled separately by _replaceNestedFn below.
    }

    // Apply inline replacements (acoth, asech, acsch) using paren-aware matching
    // so nested args like acoth(x+1) expand correctly.
    s = this._applyInlineReplacements(s);

    // Maxima if(cond, then, else) → JS ternary.  Must run before nested-fn replacements.
    s = this._replaceMathIf(s);

    // Special functions that may contain nested parentheses in their arguments
    // (e.g. u(w+(2.4)) after param substitution).  A simple [^)]* regex would
    // stop at the first ')' inside the argument, producing broken JS.
    // _replaceNestedFn walks the string counting balanced parens instead.
    s = this._replaceNestedFn(s, 'delta', (_arg) => '0');
    s = this._replaceNestedFn(s, 'u', (arg) => `(${arg} >= 0 ? 1 : 0)`);
    s = this._replaceNestedFn(s, 'rect', (arg) => `(Math.abs(${arg}) < 0.5 ? 1 : Math.abs(${arg}) === 0.5 ? 0.5 : 0)`);
    s = this._replaceNestedFn(s, 'tri',  (arg) => `(Math.abs(${arg}) < 1 ? 1 - Math.abs(${arg}) : 0)`);
    s = this._replaceNestedFn(s, 'sinc', (arg) => `(${arg} === 0 ? 1 : Math.sin(${arg}) / (${arg}))`);

    // Unrecognised Maxima names (e.g. besselj, polygamma) would produce
    // ReferenceErrors at eval time.  Replace any remaining bare identifiers
    // that look like function calls with NaN so the curve silently disappears
    // instead of crashing compile().
    s = this._stubUnknownFunctions(s);

    // Math.E**(expr) is a JS SyntaxError when expr starts with a unary minus
    // (e.g. Math.E**(-t**2+2*t-1)).  Convert all Math.E**(...) to Math.exp(...).
    s = this._replaceMathEPow(s);

    return s;
  }

  /**
   * Applies registry entries with kind:'inline' using paren-aware matching.
   * The $arg placeholder in the inline JS template is replaced with the actual
   * argument string, correctly handling nested parentheses.
   */
  private _applyInlineReplacements(expr: string): string {
    let s = expr;
    for (const fn of REGISTRY_FOR_JS) {
      if (fn.js.kind !== 'inline') continue;
      const template = fn.js.js;
      s = this._replaceNestedFn(s, fn.maxima, (arg) => template.replace(/\$arg/g, arg));
    }
    return s;
  }

  /**
   * Translates Maxima's `if(cond, then, else)` to a JS ternary `(cond ? then : else)`.
   * Handles nested parens in all three arguments.
   * Maxima also uses `=` for equality in conditions — rewritten to `===`.
   */
  private _replaceMathIf(expr: string): string {
    const occs = this._findFunctionCalls(expr, 'if');
    if (occs.length === 0) return expr;

    // Process in reverse so character positions stay valid
    let result = expr;
    for (let i = occs.length - 1; i >= 0; i--) {
      const { start, end, arg } = occs[i];
      // Split arg on commas at depth 0 to get (cond, thenExpr, elseExpr)
      const parts = this._splitAtDepth0(arg);
      if (parts.length < 2) continue;
      const [cond, thenExpr, elseExpr = 'NaN'] = parts;
      // Maxima uses = for equality; rewrite to ===, but not >= <= !=
      const jsCond = cond
        .replace(/([^><!])=([^=])/g, '$1===$2')
        .replace(/\bnot\b/g, '!')
        .replace(/\band\b/g, '&&')
        .replace(/\bor\b/g, '||');
      const replacement = `((${jsCond}) ? (${thenExpr}) : (${elseExpr}))`;
      result = result.slice(0, start) + replacement + result.slice(end);
    }
    return result;
  }

  /** Splits a string on commas that are at parenthesis depth 0. */
  private _splitAtDepth0(s: string): string[] {
    const parts: string[] = [];
    let depth = 0;
    let start = 0;
    for (let i = 0; i < s.length; i++) {
      if (s[i] === '(') depth++;
      else if (s[i] === ')') depth--;
      else if (s[i] === ',' && depth === 0) {
        parts.push(s.slice(start, i).trim());
        start = i + 1;
      }
    }
    parts.push(s.slice(start).trim());
    return parts;
  }

  /**
   * Replaces any remaining `name(arg)` calls where `name` is not a known JS or
   * helper function with the literal `NaN`, preventing ReferenceErrors at
   * evaluation time for unknown Maxima specials (besselj, polygamma, …).
   *
   * The whitelist covers every identifier that the maximaToJs pipeline can
   * legally produce: JS built-ins, Math methods, all `_helpers` names, and the
   * special-function JS helpers (rect, tri, sinc, …). Any identifier outside
   * this set that still appears as a function call is an untranslated Maxima
   * function — stub it to NaN so the curve renders as empty rather than crashing.
   *
   * Note on the Proxy alternative: `with(scope){}` is forbidden in strict mode
   * and restructuring `new Function` to accept a scope object would require
   * changing the generated JS for all expressions. The whitelist approach is
   * simpler, easier to audit, and sufficient for the backend's Maxima output.
   */
  // Whitelist built once from the registry + JS built-ins. Any identifier
  // produced by the pipeline that isn't in this set gets stubbed to NaN.
  private static readonly _KNOWN_IDENTIFIERS: ReadonlySet<string> = (() => {
    const s = new Set<string>([
      // JS keywords / globals that appear in generated code
      'Math', 'function', 'return', 'NaN', 'Infinity', 'typeof', 'void',
      'true', 'false', 'null', 'undefined', 'isFinite', 'isNaN',
      'parseInt', 'parseFloat', 'String', 'Number', 'Boolean', 'Array',
      // All Math static methods (future-proof)
      'abs', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh',
      'cbrt', 'ceil', 'clz32', 'cos', 'cosh', 'exp', 'expm1', 'floor',
      'fround', 'hypot', 'imul', 'log', 'log10', 'log1p', 'log2', 'max',
      'min', 'pow', 'random', 'round', 'sign', 'sin', 'sinh', 'sqrt',
      'tan', 'tanh', 'trunc',
      // Internal helpers for Si/Ci asymptotic expansions
      '_fAux', '_gAux',
    ]);
    // Add every JS target produced by the registry translation pipeline
    for (const fn of FUNCTION_REGISTRY) {
      const { js } = fn;
      if (js.kind === 'Math')   s.add(js.method);
      if (js.kind === 'helper') s.add(js.name);
      // signal stubs: add the maxima name so it isn't stubbed before _replaceNestedFn runs
      if (js.kind === 'stub')   s.add(fn.maxima);
    }
    return s;
  })();

  private _stubUnknownFunctions(expr: string): string {
    const known = MathUtilsService._KNOWN_IDENTIFIERS;
    // Collect unknown function calls using nested-paren-aware finder.
    // Negative lookbehind (?<!\.) ensures we don't match Math.sin as "sin".
    const re = /(?<!\.)(\b[a-zA-Z_][a-zA-Z0-9_]*\b)\s*\(/g;
    const stubs: string[] = [];
    let m: RegExpExecArray | null;
    re.lastIndex = 0;
    while ((m = re.exec(expr)) !== null) {
      const name = m[1];
      if (!known.has(name)) stubs.push(name);
    }
    // Replace each unknown function's full call (with balanced parens) with NaN
    for (const name of [...new Set(stubs)]) {
      expr = this._replaceNestedFn(expr, name, () => 'NaN');
    }
    return expr;
  }

  // ── Nested-parenthesis helpers ─────────────────────────────────────────────

  /**
   * Locates every `funcName(…)` call in `expr`, correctly tracking nested
   * parentheses so that arguments like `w+(2.4)` are captured in full.
   *
   * Returns one entry per call: the character span [start, end) of the entire
   * `funcName(arg)` token, and the `arg` string without the outer parens.
   */
  private _findFunctionCalls(
    expr: string,
    funcName: string,
  ): { start: number; end: number; arg: string }[] {
    const re = new RegExp(`\\b${funcName}\\s*\\(`, 'g');
    const results: { start: number; end: number; arg: string }[] = [];
    let m: RegExpExecArray | null;

    re.lastIndex = 0;
    while ((m = re.exec(expr)) !== null) {
      const argStart = m.index + m[0].length;
      let depth = 1;
      let j = argStart;
      while (j < expr.length && depth > 0) {
        if (expr[j] === '(') depth++;
        else if (expr[j] === ')') depth--;
        if (depth > 0) j++;
      }
      results.push({ start: m.index, end: j + 1, arg: expr.slice(argStart, j) });
    }
    return results;
  }

  /**
   * Replaces every call `funcName(arg)` in `expr` with `make(arg)`, correctly
   * handling nested parentheses inside `arg`.  A plain regex like `[^)]*` would
   * stop at the first `)` inside `arg`, which breaks expressions like
   * `u(w+(2.4))` produced when slider parameters are substituted.
   */
  private _replaceNestedFn(
    expr: string,
    funcName: string,
    make: (arg: string) => string,
  ): string {
    const occurrences = this._findFunctionCalls(expr, funcName);
    if (occurrences.length === 0) return expr;
    let result = '';
    let cursor = 0;
    for (const { start, end, arg } of occurrences) {
      result += expr.slice(cursor, start);
      result += make(arg);
      cursor = end;
    }
    return result + expr.slice(cursor);
  }

  /**
   * Parses a Maxima expression and returns the position and weight of every
   * Dirac delta term it contains.
   *
   * Algorithm per delta occurrence:
   *   1. **Position** — solve `arg(variable) = 0` via `pos = −arg(0)`.
   *      Works for the linear arguments produced by the backend: `w−a`, `w+a`, `w`.
   *   2. **Weight**  — replace *this* delta with `1`, all others with `0`,
   *      compile the resulting expression, and evaluate it.
   *      For typical Fourier outputs (e.g. `%pi*(delta(w−a)+delta(w+a))`),
   *      the modified expression is constant so the evaluation point is arbitrary;
   *      `0` is used first and `pos` is tried as a fallback.
   *
   * @param maxima    Maxima expression string (may contain `%pi`, `%e`, `^`, …).
   * @param variable  Integration / transform variable (default `'x'`).
   * @param params    Optional parameter values substituted before parsing
   *                  (same substitution as `compile`).
   */
  parseDeltaTerms(
    maxima: string,
    variable = 'x',
    params?: Record<string, number>,
  ): { pos: number; weight: number }[] {
    // Apply the same param substitution as compile()
    let expr = maxima;
    if (params) {
      for (const [name, value] of Object.entries(params)) {
        expr = expr.replace(new RegExp(`\\b${name}\\b`, 'g'), `(${String(value)})`);
      }
    }

    const occs = this._findFunctionCalls(expr, 'delta');
    if (occs.length === 0) return [];

    const results: { pos: number; weight: number }[] = [];

    for (let i = 0; i < occs.length; i++) {
      // ── 1. Position ───────────────────────────────────────────────────────
      const argFn = this.compile(occs[i].arg, variable);
      const argAt0 = argFn?.(0);
      if (argAt0 === undefined || !isFinite(argAt0)) continue;
      const pos = -argAt0;

      // ── 2. Weight ─────────────────────────────────────────────────────────
      // Build modified expression: this delta → 1, all others → 0
      let modified = '';
      let cursor = 0;
      for (let j = 0; j < occs.length; j++) {
        modified += expr.slice(cursor, occs[j].start);
        modified += j === i ? '1' : '0';
        cursor = occs[j].end;
      }
      modified += expr.slice(cursor);

      const weightFn = this.compile(modified, variable);
      if (!weightFn) continue;

      // Evaluate at 0 (constant for typical FT outputs); fallback to pos
      let weight = weightFn(0);
      if (!isFinite(weight)) weight = weightFn(pos);
      if (!isFinite(weight)) continue;

      results.push({ pos, weight });
    }

    return results;
  }

  /**
   * Converts `Math.E**BARE_EXPR` (non-parenthesised exponent) to `Math.exp(BARE_EXPR)`.
   * Handles: Math.E**x, Math.E**-x, Math.E**-x**2, Math.E**-abs(t), Math.E**-2*t.
   * The parenthesised case Math.E**(...) is left for _replaceMathEPow.
   * This must run before _fixUnaryMinusPow so that negative bare exponents like
   * Math.E**-t**2 are converted to Math.exp(-t**2) before the unary-minus fixer
   * tries to interpret them.
   */
  private _convertMathEPowBare(s: string): string {
    const token = 'Math.E**';
    let result = '';
    let i = 0;
    while (i < s.length) {
      const idx = s.indexOf(token, i);
      if (idx === -1) { result += s.slice(i); break; }
      result += s.slice(i, idx);
      const after = idx + token.length;
      if (s[after] === '(') {
        // Parenthesised — leave for _replaceMathEPow
        result += token;
        i = after;
        continue;
      }
      // Bare exponent — scan to collect it, including chains of ** (right-assoc).
      // Optionally starts with '-'
      let j = after;
      if (s[j] === '-') j++;
      // Collect the base token and any following ** chains
      let foundSomething = false;
      while (j < s.length) {
        // Collect a word token (including dots for Math.PI etc.)
        const beforeToken = j;
        while (j < s.length && /[\w.]/.test(s[j])) j++;
        if (j > beforeToken) foundSomething = true;
        // If followed by '(' it's a function call or grouped sub-expression — collect it
        if (s[j] === '(') {
          let depth = 0;
          while (j < s.length) {
            if (s[j] === '(') depth++;
            else if (s[j] === ')') { depth--; if (depth === 0) { j++; break; } }
            j++;
          }
          foundSomething = true;
        }
        // Continue if followed by ** and another token
        if (s.slice(j, j + 2) === '**') {
          j += 2;  // consume **
          if (s[j] === '-') j++;  // consume optional unary minus in sub-exponent
          // loop continues to collect next base token
        } else {
          break;
        }
      }
      if (!foundSomething) { result += token; i = after; continue; }
      let exponent = s.slice(after, j);
      // If exponent starts with '-word**...', wrap the non-sign part in parens
      // so Math.exp(-t**2) becomes Math.exp(-(t**2)) — valid JS syntax.
      if (exponent.startsWith('-') && exponent.length > 1) {
        exponent = `-(${ exponent.slice(1) })`;
      }
      result += `Math.exp(${exponent})`;
      i = j;
    }
    return result;
  }

  /**
   * Converts every `Math.E**(expr)` occurrence to `Math.exp(expr)`, correctly
   * tracking nested parentheses.  Loops until stable to handle nested exponents.
   *
   * Also avoids the JS SyntaxError that occurs when `expr` starts with a unary
   * minus directly before `**` (e.g. `-t**2+2*t-1`): in that case the argument
   * is prefixed with `0` so `-t**2` becomes the binary-subtraction `0-t**2`.
   */
  private _replaceMathEPow(expr: string): string {
    // Replace Math.E**(group) — parenthesised exponent
    const token = 'Math.E**(';
    while (expr.includes(token)) {
      const idx = expr.indexOf(token);
      const argStart = idx + token.length;
      let depth = 1, j = argStart;
      while (j < expr.length && depth > 0) {
        if (expr[j] === '(') depth++;
        else if (expr[j] === ')') depth--;
        if (depth > 0) j++;
      }
      let arg = expr.slice(argStart, j);
      // If arg is -EXPR**..., JS requires -(EXPR**...) — wrap to avoid SyntaxError.
      if (/^-\w/.test(arg) && arg.includes('**')) arg = `-(${arg.slice(1)})`;
      expr = expr.slice(0, idx) + `Math.exp(${arg})` + expr.slice(j + 1);
    }
    return expr;
  }

  /**
   * Fixes the JS SyntaxError: unary '-' cannot be the direct left operand of '**'.
   * Mathematically -x**n = -(x**n), so we wrap the whole power:
   *   -WORD**EXP    →  -(WORD**EXP)
   *   -(EXPR)**EXP  →  -((EXPR)**EXP)
   * Only fires when '-' is in a unary position (start, or after an operator / '(' / ',').
   * Runs in a loop until no more substitutions are needed (handles nested cases).
   */
  private _fixUnaryMinusPow(s: string): string {
    const isUnaryBefore = (str: string, pos: number): boolean => {
      if (pos === 0) return true;
      return /[(,=+\-*\/!&|~?:%\s]/.test(str[pos - 1]);
    };

    /** Collect a balanced-paren group starting at an open '(' at position `start`. */
    const collectGroup = (str: string, start: number): number => {
      let depth = 0, j = start;
      while (j < str.length) {
        if (str[j] === '(') depth++;
        else if (str[j] === ')') { depth--; if (depth === 0) return j; }
        j++;
      }
      return j - 1;
    };

    /** Collect a bare token (\w+ or \w+.\w+ for Math.X) starting at `start`. */
    const collectToken = (str: string, start: number): number => {
      let j = start;
      while (j < str.length && /[\w.]/.test(str[j])) j++;
      return j - 1;
    };

    for (let pass = 0; pass < 10; pass++) {
      let i = 0, out = '', changed = false;
      while (i < s.length) {
        if (s[i] === '-' && isUnaryBefore(s, i)) {
          const next = i + 1;
          let baseStart: number, baseEnd: number;

          if (s[next] === '(') {
            // Grouped base: -(...)
            baseStart = next;
            baseEnd = collectGroup(s, next);
          } else if (/[\w]/.test(s[next])) {
            // Bare token base: -word or -number
            baseStart = next;
            baseEnd = collectToken(s, next);
          } else {
            out += s[i++]; continue;
          }

          const afterBase = baseEnd + 1;
          if (s.slice(afterBase, afterBase + 2) === '**') {
            // Collect the exponent (grouped or bare token)
            const expStart = afterBase + 2;
            let expEnd: number;
            let expStr: string;
            if (s[expStart] === '(') {
              expEnd = collectGroup(s, expStart);
              expStr = s.slice(expStart, expEnd + 1);
            } else if (s[expStart] === '-' && /[\w(]/.test(s[expStart + 1] ?? '')) {
              // Negative bare exponent: **-word — wrap in parens so it becomes **(-(word))
              // This handles %e^-t^2 → Math.E**-t**2 → -(Math.E**(-(t))**2)
              // A second pass then handles the outer chain correctly.
              const afterMinus = expStart + 1;
              if (s[afterMinus] === '(') expEnd = collectGroup(s, afterMinus);
              else expEnd = collectToken(s, afterMinus);
              expStr = '(-' + s.slice(afterMinus, expEnd + 1) + ')';
            } else {
              expEnd = collectToken(s, expStart);
              expStr = s.slice(expStart, expEnd + 1);
            }

            // Wrap: -(BASE**EXP)
            out += '-(' + s.slice(baseStart, afterBase + 2) + expStr + ')';
            i = expEnd + 1;
            changed = true;
            continue;
          }
        }
        out += s[i++];
      }
      s = out;
      if (!changed) break;
    }
    return s;
  }

  // ── Reciprocal / inverse-reciprocal helpers (inlined at eval time) ──────────

  private readonly _helpers = `
    function _cot(x)  { return 1 / Math.tan(x); }
    function _sec(x)  { return 1 / Math.cos(x); }
    function _csc(x)  { return 1 / Math.sin(x); }
    function _acot(x) { return Math.PI / 2 - Math.atan(x); }
    function _asec(x) { return Math.acos(1 / x); }
    function _acsc(x) { return Math.asin(1 / x); }
    function _sech(x) { return 1 / Math.cosh(x); }
    function _csch(x) { return 1 / Math.sinh(x); }
    function _coth(x) { return Math.cosh(x) / Math.sinh(x); }
    function _gamma(x) {
      if (x <= 0 && x === Math.floor(x)) return Infinity;
      if (x < 0.5) return Math.PI / (Math.sin(Math.PI * x) * _gamma(1 - x));
      x -= 1;
      const c = [0.99999999999980993,676.5203681218851,-1259.1392167224028,
        771.32342877765313,-176.61502916214059,12.507343278686905,
        -0.13857109526572012,9.9843695780195716e-6,1.5056327351493116e-7];
      let a = c[0];
      const t = x + 7.5;
      for (let i = 1; i < 9; i++) a += c[i] / (x + i);
      return Math.sqrt(2 * Math.PI) * Math.pow(t, x + 0.5) * Math.exp(-t) * a;
    }
    function _factorial(n) { return _gamma(n + 1); }
    function _erf(x) {
      const t = 1 / (1 + 0.3275911 * Math.abs(x));
      const y = 1 - (((((1.061405429 * t - 1.453152027) * t) + 1.421413741) * t - 0.284496736) * t + 0.254829592) * t * Math.exp(-x * x);
      return x >= 0 ? y : -y;
    }
    function _erfc(x) { return 1 - _erf(x); }
    const _EG = 0.5772156649015329;
    function _Ei(x) {
      if (x === 0) return -Infinity;
      if (x < 0) return -_E1(-x);
      if (x < 6) {
        let s = 0, t = x;
        for (let n = 1; n <= 50; n++) {
          s += t;
          const tn = t * (x * n / ((n + 1) * (n + 1)));
          if (Math.abs(tn) < 1e-13 * Math.abs(s) && n > 3) break;
          t = tn;
        }
        return _EG + Math.log(x) + s;
      }
      let s = 1, t = 1;
      for (let n = 1; n <= 25; n++) { const tn = t * (n / x); if (Math.abs(tn) >= Math.abs(t)) break; t = tn; s += t; }
      return Math.exp(x) / x * s;
    }
    function _E1(x) {
      if (x <= 0) return NaN;
      if (x < 6) {
        let s = 0, t = x;
        for (let n = 1; n <= 50; n++) {
          s += t;
          const tn = t * (-n * x / ((n + 1) * (n + 1)));
          if (Math.abs(tn) < 1e-13 * Math.abs(s) && n > 3) break;
          t = tn;
        }
        return -_EG - Math.log(x) + s;
      }
      let s = 1, t = 1;
      for (let n = 1; n <= 25; n++) { const tn = t * (-n / x); if (Math.abs(tn) >= Math.abs(t)) break; t = tn; s += t; }
      return Math.exp(-x) / x * s;
    }
    function _fAux(x) {
      let s = 1, t = 1, x2 = x * x;
      for (let n = 1; n <= 25; n++) { const tn = t * (-(2*n) * (2*n-1) / x2); if (Math.abs(tn) >= Math.abs(t)) break; t = tn; s += t; }
      return s / x;
    }
    function _gAux(x) {
      let s = 1, t = 1, x2 = x * x;
      for (let n = 1; n <= 25; n++) { const tn = t * (-(2*n+1) * (2*n) / x2); if (Math.abs(tn) >= Math.abs(t)) break; t = tn; s += t; }
      return s / (x * x);
    }
    function _Si(x) {
      const a = Math.abs(x);
      if (a < 4) {
        let s = 0, t = x, x2 = x * x;
        for (let n = 0; n < 30; n++) { s += t; t *= -x2 * (2*n+1) / ((2*n+2) * (2*n+3) * (2*n+3)); }
        return s;
      }
      // Si is odd: Si(-x) = -Si(x), so sign wraps the entire asymptotic expression
      return Math.sign(x) * (Math.PI / 2 - _fAux(a) * Math.cos(a) - _gAux(a) * Math.sin(a));
    }
    function _Ci(x) {
      if (x <= 0) return NaN;
      if (x < 4) {
        let s = 0, t = -x * x / 4, x2 = x * x;
        for (let n = 1; n <= 30; n++) { s += t; t *= -x2 * 2*n / ((2*n+2) * (2*n+2) * (2*n+1)); }
        return _EG + Math.log(x) + s;
      }
      return _fAux(x) * Math.sin(x) - _gAux(x) * Math.cos(x);
    }
    function _Shi(x) {
      if (x === 0) return 0;
      const a = Math.abs(x);
      if (a < 10) {
        let s = 0, t = x, x2 = x * x;
        for (let n = 0; n < 50; n++) {
          s += t;
          const tn = t * x2 * (2*n+1) / ((2*n+2) * (2*n+3) * (2*n+3));
          if (Math.abs(tn) < 1e-13 * Math.abs(s) && n > 3) break;
          t = tn;
        }
        return s;
      }
      return x > 0 ? (_Ei(x) + _E1(x)) / 2 : -(_Ei(a) + _E1(a)) / 2;
    }
    function _Chi(x) {
      if (x <= 0) return NaN;
      if (x < 10) {
        let s = 0, t = x * x / 4, x2 = x * x;
        for (let n = 1; n <= 50; n++) {
          s += t;
          const tn = t * x2 * 2*n / ((2*n+2) * (2*n+2) * (2*n+1));
          if (Math.abs(tn) < 1e-13 * Math.abs(s) && n > 3) break;
          t = tn;
        }
        return _EG + Math.log(x) + s;
      }
      return (_Ei(x) - _E1(x)) / 2;
    }
    function _li(x) { return x <= 0 ? NaN : _Ei(Math.log(x)); }

    // ── Incomplete gamma (series + continued-fraction) ─────────────────────────
    // Lower incomplete gamma γ(a,x) via power series — converges for all x when a>0
    function _gamma_lower_series(a, x) {
      if (x <= 0) return 0;
      let term = 1 / a, s = term;
      for (let n = 1; n <= 200; n++) {
        term *= x / (a + n);
        s += term;
        if (Math.abs(term) < 1e-13 * Math.abs(s)) break;
      }
      return Math.exp(-x + a * Math.log(x)) * s;
    }
    // Upper incomplete gamma Γ(a,x) via Lentz continued fraction — converges for large x
    function _gamma_upper_cf(a, x) {
      let f = x + 1 - a, C = f, D = 0, delta;
      if (Math.abs(f) < 1e-30) f = 1e-30;
      C = f; D = 0;
      for (let n = 1; n <= 200; n++) {
        const an = n * (a - n), bn = x + 2 * n + 1 - a;
        D = bn + an * D; if (Math.abs(D) < 1e-30) D = 1e-30; D = 1 / D;
        C = bn + an / C; if (Math.abs(C) < 1e-30) C = 1e-30;
        delta = C * D;
        f *= delta;
        if (Math.abs(delta - 1) < 1e-13) break;
      }
      return Math.exp(-x + a * Math.log(x)) / f;
    }
    // gamma_incomplete_lower(a, x) = γ(a, x)  [Maxima: gamma_incomplete_lower]
    function _gamma_incomplete_lower(a, x) {
      if (a <= 0 || x < 0) return NaN;
      if (x === 0) return 0;
      return (x < a + 1) ? _gamma_lower_series(a, x)
                         : _gamma(a) - _gamma_upper_cf(a, x);
    }
    // gamma_incomplete(a, x) = Γ(a, x)  [Maxima: gamma_incomplete — upper]
    function _gamma_incomplete(a, x) {
      if (a <= 0 || x < 0) return NaN;
      if (x === 0) return _gamma(a);
      return (x < a + 1) ? _gamma(a) - _gamma_lower_series(a, x)
                         : _gamma_upper_cf(a, x);
    }
    // gamma_incomplete_regularized(a, x) = Q(a,x) = Γ(a,x)/Γ(a)  [Maxima: gamma_incomplete_regularized]
    function _gamma_incomplete_regularized(a, x) {
      if (a <= 0 || x < 0) return NaN;
      return _gamma_incomplete(a, x) / _gamma(a);
    }

    // ── Beta function ──────────────────────────────────────────────────────────
    // beta(a, b) = Γ(a)Γ(b)/Γ(a+b)
    function _beta(a, b) {
      if (a <= 0 || b <= 0) return NaN;
      return _gamma(a) * _gamma(b) / _gamma(a + b);
    }
  `;
}
